<a href="https://colab.research.google.com/github/immranazry/Pytorch-Tutorial/blob/main/Tensor_Math_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import numpy as np


In [2]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

In [3]:
#Addition
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [4]:
#Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [6]:
#Subtraction
tensor_b - tensor_a

tensor([5, 5, 5, 5, 5])

In [7]:
#Subtraction Longhand
torch.sub(tensor_b, tensor_a)

tensor([5, 5, 5, 5, 5])

In [8]:
#Multiplication
tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])

In [9]:
#Multiplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [10]:
#Division
tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [11]:
#Division Longhand
torch.div(tensor_b, tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [13]:
#Modulus
tensor_b % tensor_a

tensor([0, 1, 2, 1, 0])

In [15]:
#Modulus longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1, 0])

In [18]:
#Exponents
tensor_a ** tensor_b

tensor([      1,     128,    6561,  262144, 9765625])

In [19]:
#Exponents Longhand
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [15]:
#Reassignment_
tensor_c = torch.tensor([1,2,3,4])
tensor_d = torch.tensor([5,6,7,8])

In [18]:
#tensor_c = tensor_c + tensor_d (normal method)
tensor_c.add_(tensor_d) #underscore method
tensor_c

tensor([16, 20, 24, 28])

In [19]:
#Another way to write longhand (Reassigned tensor_c + tensor_d)
tensor_c.add(tensor_d)

tensor([21, 26, 31, 36])