<a href="https://colab.research.google.com/github/immranazry/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Initialization

In [5]:
import torch
import numpy as np

Python Lists

In [7]:
list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays  - More powerful than python lists

In [9]:
np1 = np.random.rand(3, 4) # creates a 3 by 4 matrix (numpy array) with random values
np1

array([[0.30481063, 0.57023093, 0.50178019, 0.05344527],
       [0.09774439, 0.82673565, 0.14190686, 0.79392862],
       [0.95315068, 0.67775515, 0.51486843, 0.09498781]])

In [10]:
np1.dtype # outputs datatype of values in array

dtype('float64')

Tensors - More powerful than numpy arrays

In [18]:
tensor_2d = torch.randn(3, 4) # creates a 3 by 4 matrix (Tensor) with random values
tensor_2d
#tensor_2d.dtype
# tensors by default are float32

tensor([[ 1.3517,  0.8949,  0.0752, -0.1167],
        [-0.9523,  1.6002, -0.1562,  0.9863],
        [ 0.4738,  0.3980, -0.3092,  0.2090]])

In [12]:
tensor_3d = torch.zeros(2, 3, 4) # creates 2 rows of 3 by 4 tensors
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of my numpy array
my_tensor = torch.tensor(np1)
my_tensor
# datatype is float64 because the numpy array (np1) was float 64

tensor([[0.3048, 0.5702, 0.5018, 0.0534],
        [0.0977, 0.8267, 0.1419, 0.7939],
        [0.9532, 0.6778, 0.5149, 0.0950]], dtype=torch.float64)