<a href="https://colab.research.google.com/github/immranazry/Pytorch-Tutorial/blob/main/Tensor_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View (basically does the same thing)
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape if we don't know the number of items using -1 (-1 can be used on both sides)
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# With reshape and view, they will update
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_torch4 = my_torch3.reshape(2, -1)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch3[1] = 4141 # update value at index 1
my_torch3

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [10]:
my_torch4 # it auto updates

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [11]:
# Slices
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Grab a specific item
my_torch5[4]

tensor(4)

In [14]:
# Grab & Slice
my_torch6 = my_torch5.reshape(5,-1)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
my_torch6[1]

tensor([2, 3])

In [21]:
my_torch6[:, 1]

tensor([1, 3, 5, 7, 9])

In [22]:
# Return column
my_torch6[:, 1 :]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])